### ISSUE TITLE
Sending Emails on TLS 1.2 [sf#13]

### ISSUE THREAD

**Issue by nilnull** [nilnull/AIM#12]
**Reported by naveenpapagari on 2017-01-23 05:56 UTC**
I have been using Aegis Implicit Mail (AIM) to send mails over ssl for some time. We have recently upgraded to TLS 1.2 and  now i am not able to send any mails. I have been getting error saying - The client and server cannot communicate, because they do not possess a common algorithm.  Need help on this ... Thank you

**Comment by nilnull** [comment]
**Commented by naveenpapagari on 2017-01-23 05:57 UTC**
I have been using Aegis Implicit Mail (AIM) to send mails over ssl for some time. We have recently upgraded to TLS 1.2 and now i am not able to send any mails. I have been getting error saying - The client and server cannot communicate, because they do not possess a common algorithm. Need help on this ... Thank you

**Comment by nilnull** [comment]
**Commented by nilnull on 2017-01-23 09:39 UTC**
Hello and thanks for choosing AIM, can you check if your certificate has been changed? would you provide more detail? can you debug using source code and send us the log? thanks again

**Comment by nilnull** [comment]
**Commented by naveenpapagari on 2017-01-23 18:21 UTC**
Hello Araz .. Thanks for replying back .. 

Following are the details - 

Message : 
The client and server cannot communicate, because they do not possess a common algorithm

StackTrace :
at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
   at AegisImplicitMail.SmtpSocketConnection.Open(String host, Int32 port, SslMode isSsl, Int32 timeout)
   at AegisImplicitMail.SmtpSocketClient.EsablishSmtp()

Code : 
var mailer = new MimeMailer(ConfigurationManager.AppSettings["SMTPServer"], Convert.ToInt32(ConfigurationManager.AppSettings["SMTPServerPort"]));
mailer.User = ConfigurationManager.AppSettings["SMTPUserName"];
mailer.Password = ConfigurationManager.AppSettings["SMTPPassword"];
mailer.SslType = SslMode.Ssl;
mailer.AuthenticationMode = AuthenticationType.Base64;               
mailer.SendCompleted += compEvent;
mailer.SendMailAsync(mymessage);

I have even changed SslType to TLS and tried and it gives out the same error -

"We couldn't connect to server, server is clossing".

**Comment by nilnull** [comment]
**Commented by nilnull on 2017-01-23 18:34 UTC**
Dear Naveen, I suspect that error has nothing todo with AIM. Its a generic c#  error and might be caused  by invalid server configurations, multiple protocols, disables ssl and
